# Generated by Django 5.1.2 on 2024-11-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_recordeddata_alert_type_recordeddata_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
