# Generated by Django 5.1.3 on 2024-11-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alerts_is_active_vehiclelocation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
